# Generated by Django 5.0.6 on 2026-06-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('event_date', models.CharField(max_length=100)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('whatsapp_link', models.CharField(default='https://wa.me/918015913057', max_length=500)),
                ('booking_link', models.CharField(blank=True, default='', max_length=500)),
                ('event_status', models.CharField(choices=[('upcoming', 'Upcoming'), ('past', 'Past Event')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
